apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: tnunes-test-crossplane-local
  annotations:
    crossplane.io/external-name: tnunes-test-crossplane-local
spec:
  deletionPolicy: Delete
  forProvider:
    acl: private
    locationConstraint: us-east-1
    publicAccessBlockConfiguration:
      ignorePublicAcls: true
      blockPublicAcls: true
      blockPublicPolicy: true
      restrictPublicBuckets: true
    paymentConfiguration:
      payer: BucketOwner
    tagging:
      tagSet:
        - key: "team"
          value: "iac"
        - key: "bu"
          value: "tech_cross"
        - key: "project"
          value: "crossplane"
  providerConfigRef:
    name: iac-lab