apiVersion: v1
kind: ConfigMap
metadata:
  name: strider-api-config
  namespace: strider
  labels:
    app: strider-api
    tier: pods
data:
  SERVER_PORT: "8080"
  SERVER_DEBUG: "false"
  DB_HOST: "strider-db-svc"
  DB_PORT: "3306"
  DB_NAME: "strider"
  DB_USER: "root"
  DB_PASS: "secret"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: strider-db-config
  namespace: strider
  labels:
    app: strider-db
data:
  MYSQL_ROOT_USER: "root"
  MYSQL_ROOT_PASSWORD: "secret"
  MYSQL_DATABASE: "strider"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strider-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS `strider`;
    USE `strider`;
    CREATE TABLE IF NOT EXISTS `strider`.`posts` (
        `id` INT AUTO_INCREMENT NOT NULL,
        `uuid` VARCHAR(36) NOT NULL,
        `type` ENUM('original', 'repost', 'quote') NOT NULL,
        `text` VARCHAR(777) NOT NULL,
        `user_id` INT NOT NULL,
        `post_id` INT,
        `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        INDEX `uuid_index` (`uuid`),
        PRIMARY KEY (`id`),
        FOREIGN KEY (`post_id`) REFERENCES `posts`(`id`)
    ) ENGINE = INNODB;