apiVersion: apps/v1
kind: Deployment
metadata:
  name: strider-db
  namespace: strider
spec:
  selector:
    matchLabels:
      app: strider-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: strider-db
    spec:
      containers:
      - name: strider-db
        image: mysql:latest
        envFrom:
          - configMapRef:
              name: strider-db-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: strider-db
        volumeMounts:
        - name: strider-db-persistent-storage
          mountPath: /var/lib/mysql
        - name: strider-initdb
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: strider-db-persistent-storage
        persistentVolumeClaim:
          claimName: strider-db-pv-claim
      - name: strider-initdb
        configMap:
          name: strider-initdb-config