apiVersion: v1
kind: Service
metadata:
  name: strider-api-svc
  namespace: strider
  labels:
    app.kubernetes.io/name: strider-api
spec:
  selector:
    app: strider-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
