apiVersion: v1
kind: Service
metadata:
  name: strider-api-nodeport-svc
  namespace: strider
spec:
  type: NodePort
  selector:
    app: strider-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
