apiVersion: v1
kind: Namespace
metadata:
  name: ms-deletion-fausthanos-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fausthanos-sa
  namespace: ms-deletion-fausthanos-test
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fausthanos-clusterrole
  namespace: ms-deletion-fausthanos-test
rules:
- apiGroups: ["", "apps", "extensions", "batch"]
  resources: ["*"]
  verbs: ["*"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fausthanos-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: fausthanos-sa
    namespace: ms-deletion-fausthanos-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fausthanos-clusterrole
---
apiVersion: v1
kind: Secret
metadata:
  name: fausthanos-secret
  namespace: ms-deletion-fausthanos-test
  annotations:
    kubernetes.io/service-account.name: fausthanos-sa
type: kubernetes.io/service-account-token
