apiVersion: v1
kind: Namespace
metadata:
  name: ms-test-deletion-one
---
apiVersion: v1
kind: Service
metadata:
  name: test-deletion-one-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deletion-one-api
  namespace: ms-test-deletion-one
  labels:
    app: test-deletion-one-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-deletion-one-api
  template:
    metadata:
      namespace: ms-test-deletion-one
      labels:
        app: test-deletion-one-api
    spec:
      containers:
      - name: test-deletion-one-api
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: http-web-svc
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-deletion-one-cronjob
  namespace: ms-test-deletion-one
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-deletion-one-cronjob
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
