apiVersion: v1
kind: ServiceAccount
metadata:
	name: {{ .Values.app.name }}
	labels:
		chart: {{ .Chart.Name }}
		template: {{ .Template.Name }}
secrets:
	{{- if .Values.extraServiceAccount }}
	- name: {{ .Values.extraServiceAccount }}
	{{- else }}
	- name: default-secret
	{{- end }}