apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
secrets:
  {{- if not (empty .Values.extraServiceAccount) }}
    - name: {{ .Values.extraServiceAccount }}
  {{ else }}
    - name: default-secret
  {{- end }} 