apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name }}
  labels:
    chart: {{ .Chart.Name}}-{{ .Chart.Version }}
    template: {{ .Template.Name }}
    {{- range $label, $value := .Values.global.labels }}
    {{ $label }}: {{ $value | quote }}
    {{- end }}
    
secrets:
  {{- if not (empty .Values.extraServiceAccount) }}
    - name: {{ .Values.extraServiceAccount }}
  {{ else }}
    - name: default-secret
  {{- end }} 